DEFAULT_FONT_COLOR = "#bf616a"
DEFAULT_WARN_TEXT = "  PRODUCTION SERVER:"
# ALLOWED_WARN_TEXT_PATTERN = r'^[a-zA-Z0-9\s!@#$%^&*()-_=+[\]{};:"<>,.?/\\]*$'
ALLOWED_WARN_TEXT_PATTERN = r"^[\s\S]{0,100}$"
